### ISSUE TITLE
License / Usage guidelines

### ISSUE THREAD

**Issue by nook24** [naemon/naemon.github.io#103]
Hi all,
I would like to add a searchable list of all available Naemon default macros to the [openITCOCKPIT](https://github.com/it-novum/openITCOCKPIT/tree/ORM ) interface:
![Bildschirmfoto 2019-09-05 um 17 07 24](https://user-images.githubusercontent.com/9019992/64354635-19075880-d000-11e9-9554-6819a5dd6e43.png)

Can i just copy and paste the macro description from https://raw.githubusercontent.com/naemon/naemon.github.io/master/documentation/usersguide/macrolist.md? I don't want to get in trouble with you guys :)

**Comment by sni** [comment]
we discussed this internally and i created a PR to address this issue: https://github.com/naemon/naemon.github.io/pull/104
So this website is opensource and gplv3, so you can use it basically at the same terms as the other parts of naemon.

**Comment by nook24** [comment]
Many thanks for your quick reply.

I think due to the strict copy left of the GPL some other license may sute better for this kind of purpose. ( [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) maybe?)

Please don't get me wrong. I don't want to steal any content and have no problem to add link to the source website.

**Comment by sni** [comment]
the thing is, we move parts from the different sub-repositories back and forth ourselves too, so we though using the same license for all naemon things makes things easier.

**Comment by nook24** [comment]
This makes sense.
Fine for me - I will close this.

PS: See you at OSMC 🎉
