### ISSUE TITLE
You can use this repo: https://labs.consol.de/repo/stable/#_8

### ISSUE THREAD

**Issue by manugu87** [naemon/naemon.github.io#148]
You can use this repo: https://labs.consol.de/repo/stable/#_8
The OBS builds stopped working with all this centos BS.

_Originally posted by @sni in https://github.com/naemon/naemon.github.io/issues/147#issuecomment-1381496896_

**Comment by manugu87** [comment]
This repo is valid for RH8, RH9, Rocky/Almalinux 8 and 9?

**Comment by sni** [comment]
it's build with rocky 8, but should work with all compatible rhel 8 variants.
