### ISSUE TITLE
Problems installing on Debian

### ISSUE THREAD

**Issue by zoredache** [naemon/naemon.github.io#60]
I am running debian 8.x so I went to the `quickstart-debian` page.  Part of the instructions is to use wget to retrieve a bunch of files, then use `dpkg -i naemon*.deb` to install them.  The problem here is that you have a package named `libnaemon`, that isn't in the list of things to download with curl, and wouldn't be matched by the wildcard pattern used with dpkg.  If you follow these steps the install fails, because it is missing libnaemon.  The documentation should be updated.

Ref:
- https://github.com/naemon/naemon.github.io/blob/master/documentation/usersguide/quickstart-debian.md
- https://github.com/naemon/naemon.github.io/blame/master/documentation/usersguide/quickstart-debian.md#L45

As an alternative, you could post a set of directions similar to this in the quickstart, that would let people download the packages, and then add a local apt repo.  Using the wget in recursive mode would
automatically get all the packages in the directory.  Also you wouldn't need to have to instruct the users to manually pre-install the dependencies.

```
# update this to be the base URL for your release/arch
releaseurl='https://labs.consol.de/naemon/release/v1.0.3/debian8/amd64/'
# update this to be a local path where you want to cache the packages
packagedir='/usr/src/naemon/'
# make folder to cache packages
mkdir -p ${packagedir}
cd ${packagedir}
# download the packages
wget --recursive --timestamping \
     --no-parent --cut-dirs=2 --no-host-directories \
     $releaseurl
# build an packages file for apt
cd ${packagedir}v1.0.3/
dpkg-scanpackages . /dev/null > Packages
# add to apt
echo "deb file:${packagedir}v1.0.3/ ./" > /etc/apt/sources.list.d/99naemon.list
# install (will show up as untrusted, since this is not gpg signed)
apt-get update && apt-get install naemon
```

**Comment by sni** [comment]
We really should just point to the labs repository.

**Comment by catharsis** [comment]
Yeah, why would we need to download dependencies manually anyway? (Perhaps we are afraid `apt` might strain itself doing all that heavy lifting?)

**Comment by jryberg** [comment]
Oh, this is artifacts from early days. We should use the repo instead in
all documentation.

// Johan

2016-05-31 7:56 GMT+02:00 Anton Löfgren <notifications@github.com>:
