### ISSUE TITLE
Unsupported markdown engine

### ISSUE THREAD

**Issue by pengi** [naemon/naemon.github.io#62]
Got this mail automatically after fixing a typo on the page:

---
### The page build completed successfully, but returned the following warning:

You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by jacobbaungard** [comment]
Closing this due to: c2187c61e8768e970aaa24b0645215ee88e9a939#diff-aeb42283af8ef8e9da40ededd3ae2ab2
