### ISSUE TITLE
"Upgrading" page is broken on naemon.org

### ISSUE THREAD

**Issue by wchristian** [naemon/naemon.github.io#66]
Specifically this one: http://www.naemon.org/documentation/usersguide/upgrading.html

The "Upgrading From Nagios 2.x" section title is flowed into the list above.

It is rendered fine here: https://github.com/naemon/naemon.github.io/blob/master/documentation/usersguide/upgrading.md

**Comment by sni** [comment]
Thanks, should be better now.

**Comment by wchristian** [comment]
Still looks borked to me. This should be a section title:

![image](https://user-images.githubusercontent.com/175467/27765221-510d3d98-5eac-11e7-9d94-49735281dd32.png)

**Comment by sni** [comment]
strange, seems like the fix is not yet live. I will have a look at it tomorrow.

**Comment by wchristian** [comment]
Still not fixed. https://github.com/naemon/naemon.github.io/commit/d27bdef66abf6c00ff34be74ac2acbf586caf0ec also does not look like it would address that.

**Comment by sni** [comment]
I thought the underlines befor the section title broke the markdown parsing because it looked good on my local jekyll preview. However, it seems like githubs jekyll converts the markdown somehow slightly different.

**Comment by wchristian** [comment]
I suspect it might be that it expects the <li> tags to be closed.

**Comment by sni** [comment]
At least i am able to reproduce it locally now after setting up a new jekyll environment according to https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
It looks like severall other pages are broken now as well, ex: http://www.naemon.org/documentation/usersguide/objectdefinitions.html

We previously used the redcarpet markdown interpreter which was deprecated for quite some time, maybe they removed it now and we need to migrate.

**Comment by wchristian** [comment]
I note the objectdefinitions page also breaks at the last element in a list.

**Comment by sni** [comment]
Alright, should be fixed now. Let me know if anything else looks weird on the page.

**Comment by wchristian** [comment]
Looks good now. :)
