### ISSUE TITLE
Formatting Issues with (|) symbol

### ISSUE THREAD

**Issue by Herkum** [naemon/naemon.github.io#86]
the md format gets confused when using the | (the pipe character) in certain situations.  I have a branch request

**Comment by sni** [comment]
great, please create a pull request if you have some changes.

**Comment by Herkum** [comment]
I would be happy too if I can get permissions to create a branch, can someone help with with that?

**Comment by sni** [comment]
Thats not how github works, you can do simple changes directly on github or fork the project, apply your changes and create a pull request. There is no need for a separate branch.
Read more here: https://help.github.com/articles/editing-files-in-another-user-s-repository/
